#!/bin/bash
set -e

cd $(dirname $0)/..

if [ -z "$PLATFORM" ]; then
    PLATFORM="amd64"
fi

: ${CONFIG:=$(pwd)/config}
: ${DIST:=$(pwd)/dist}

echo "about to build ${ARCH}"

mkdir -p ${DIST}/artifacts

./scripts/build-busybox "build" ${CONFIG}/${PLATFORM}/buildroot-config-static ${CONFIG}/busybox-dynamic.config
./scripts/package ${PLATFORM}
